name: dtogen_cli
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  args: ^2.3.1
  path: ^1.8.0
  dtogen:
    git:
      url: https://github.com/qyre-ab/dtogen.git
      path: packages/dtogen

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
